disabled_rules:
  - trailing_whitespace
  - line_length
  - large_tuple
  - force_unwrapping
  - function_body_length
  - identifier_name
  - multiple_closures_with_trailing_closure
  - unused_closure_parameter
opt_in_rules:
  - empty_count
excluded:
  - Pods
  - Carthage
  - .build
  - IronFive.xcodeproj
