name: IronFive
options:
  bundleIdPrefix: com.antigravity
targets:
  IronFive:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_KEY_CFBundleDisplayName: IronFive
        INFOPLIST_KEY_UISupportedInterfaceOrientations:
          [UIInterfaceOrientationPortrait]
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.0
        DEVELOPMENT_TEAM: ""
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: IronFive needs permission to log your workouts to Apple Health.
        INFOPLIST_KEY_NSHealthShareUsageDescription: IronFive needs permission to read your heart rate and active energy during workouts.
        INFOPLIST_KEY_UIBackgroundModes: [workout-processing]
        CODE_SIGN_ENTITLEMENTS: Sources/IronFive.entitlements
schemes:
  IronFive:
    build:
      targets:
        IronFive: [all]
